# Generated by Django 5.0.2 on 2024-02-11 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='listings.thread'),
            preserve_default=False,
        ),
    ]
